# Generated by Django 4.2.4 on 2023-08-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_order_product_quantity_available_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
    ]
